# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(433, 205)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.Armenian, QtCore.QLocale.Armenia))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.te_word = QtWidgets.QTextEdit(Dialog)
        self.te_word.setEnabled(True)
        self.te_word.setGeometry(QtCore.QRect(50, 20, 191, 21))
        self.te_word.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.te_word.setAcceptDrops(True)
        self.te_word.setObjectName("te_word")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(50, 61, 41, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.te_mean = QtWidgets.QTextEdit(Dialog)
        self.te_mean.setGeometry(QtCore.QRect(140, 60, 211, 21))
        self.te_mean.setObjectName("te_mean")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 75, 461, 41))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.te_enges = QtWidgets.QTextEdit(Dialog)
        self.te_enges.setGeometry(QtCore.QRect(40, 140, 391, 21))
        self.te_enges.setObjectName("te_enges")
        self.te_chnes = QtWidgets.QTextEdit(Dialog)
        self.te_chnes.setGeometry(QtCore.QRect(40, 170, 391, 21))
        self.te_chnes.setObjectName("te_chnes")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(360, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 40, 561, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "单词"))
        self.label_2.setText(_translate("Dialog", "词性"))
        self.comboBox.setItemText(0, _translate("Dialog", "n"))
        self.comboBox.setItemText(1, _translate("Dialog", "v"))
        self.comboBox.setItemText(2, _translate("Dialog", "pron"))
        self.comboBox.setItemText(3, _translate("Dialog", "adj"))
        self.comboBox.setItemText(4, _translate("Dialog", "adv"))
        self.comboBox.setItemText(5, _translate("Dialog", "prep"))
        self.comboBox.setItemText(6, _translate("Dialog", "pron"))
        self.comboBox.setItemText(7, _translate("Dialog", "conj"))
        self.comboBox.setItemText(8, _translate("Dialog", "num"))
        self.comboBox.setItemText(9, _translate("Dialog", "int"))
        self.label_3.setText(_translate("Dialog", "释义"))
        self.label_4.setText(_translate("Dialog", "例句"))
        self.label_5.setText(_translate("Dialog", "中"))
        self.label_6.setText(_translate("Dialog", "英"))
        self.pushButton.setText(_translate("Dialog", "提交"))

